:heavy_exclamation_mark: Github Workflow Test 1

diff --git a/.github/workflows/amibuild.yml b/.github/workflows/amibuild.yml
--- a/.github/workflows/amibuild.yml
+++ b/.github/workflows/amibuild.yml
@@ -56,7 +56,7 @@ jobs:
         run: |
           zip -r webapp.zip ./
           pwd ./webapp
-      - name: Step 3 - Configure AWS Credentials
+      - name: Step 3 - Configure AWS DEV Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
@@ -84,3 +84,47 @@ jobs:
           target: ami.pkr.hcl
         env:
           PACKER_LOG: 1
+      - name: Step 7 - Configure AWS PROD Credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
+          aws-region: ${{ env.AWS_REGION }}
+      - name: Step 8 - Instance Refresh 
+        run: | 
+         sudo apt install -y jq
+         ASG_NAME={{secrets.ASG_NAME}}
+         LAUNCH_CONFIG={{secrets.LAUNCH_CONFIG}}
+         IMAGE=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d':' -f2)
+
+          IMAGE_ID=$(jq -n \
+            --arg img "$IMAGE" \
+            '{"ImageId": $img}')
+
+          aws ec2 create-launch-template-version \
+            --launch-template-name "$LAUNCH_CONFIG" \
+            --version-description updateAMI --source-version 1 \
+            --launch-template-data="$IMAGE_ID" \
+            
+          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME \
+            --launch-template LaunchTemplateName="$LAUNCH_CONFIG",Version='$Latest' \
+            
+          aws autoscaling start-instance-refresh \
+            --auto-scaling-group-name $ASG_NAME \
+
+          printf "\nInstance refresh in progress ...\n"
+          while true;
+          do
+            instance_refresh_status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $ASG_NAME \
+              --query "InstanceRefreshes[0].Status" --output text)
+            if [ "$instance_refresh_status" = "Successful" ]; then
+              printf "\nInstance refresh successful!"
+              break
+            fi
+            if [ "$instance_refresh_status" = "Cancelling" ] || [ "$instance_refresh_status" = "Cancelled" ] || [ "$instance_refresh_status" = "Failed" ]; then
+              printf "\nInstance refresh failed!"
+              exit 1
+            fi
+            echo -ne "."
+            sleep 10
+          done
